---
- hosts: node1
  become: true
  tasks:
     - name: Install Python
       apt: pkg=python-minimal state=installed update_cache=true
     - name: Install NodeJS
       apt: pkg=nodejs state=installed update_cache=true
     - name: Install NPM
       apt: pkg=npm state=installed update_cache=true
    #  - name: Link
    #    command: sudo ln -s /usr/bin/nodejs /usr/bin/node
    # Python dependecies.
     - name: Install pip
       apt: pkg=python-pip state=installed update_cache=true
     - name: Install python dev
       apt: pkg=python-dev state=installed update_cache=true
     - name: Install ps-util
       command: pip install psutil
     - name: Install Twilio
       command: pip install twilio

    # - name:

    # Start redis server
    # - name: Start redis
    #   command: redis-server --daemonize yes

    # Send sms script
    # - name: Start messaging server.
     #  command: sh /home/ubuntu/startMonitor.sh

# - hosts: nodeDGO
#   become: true
#   tasks:
#     - name: Installs nginx web server
#       apt: pkg=nginx state=installed update_cache=true
#       notify:
#         - start nginx
#
#   handlers:
#     - name: start nginx
#       service: name=nginx state=started
